name: Test

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  test:
    name: Node 12 - ubuntu - with coverage
    runs-on: ubuntu-latest
      with:
        node-version: 12
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Volta
        uses: volta-cli/action@v1
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn jest --coverage

  nodeX:
    name: Node ${{ matrix.node-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
      with:
        node-version: ${{ matrix.node-version }}
    timeout-minutes: 10

    needs: [test]

    strategy:
      matrix:
        os: [ubuntu, windows]
        node-version: [10, 12, 14, 15]

        # excluded because it is the `test` job above
        exclude:
          - os: ubuntu
            node-version: 12

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Volta
        uses: volta-cli/action@v1
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --ignore-engines
      - name: Test
        run: yarn jest

  floating-dependencies:
    name: Floating Dependencies
    runs-on: ubuntu-latest
      with:
        node-version: 12
    timeout-minutes: 10

    needs: [test]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Volta
        uses: volta-cli/action@v1
      - name: Install Dependencies
        run: yarn install --no-lockfile
      - name: Test
        run: yarn jest
